server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003 #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false  #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    #假设有个物业中心，物业中心有一个注册表是登记所有住户的（即每个微服务），eureka服务端就是物业中心，物业中心不需要把自己登记到花名册。
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
